"""Data generators for diagnostics examples.

Generates synthetic financial return series for testing diagnostic tools:
- Standard GARCH(1,1) returns (S&P 500 calibration)
- Misspecified data (EGARCH DGP) for sign bias detection
- Structural break data for Nyblom stability test

All generators use fixed seeds for perfect reproducibility.
"""

import numpy as np
import pandas as pd


def generate_garch11_returns(
    n: int = 2500,
    omega: float = 1.5e-6,
    alpha: float = 0.08,
    beta: float = 0.91,
    mu: float = 0.0004,
    seed: int = 42,
    start_date: str = "2014-01-02",
) -> pd.DataFrame:
    """Generate returns from a GARCH(1,1) process.

    Parameters
    ----------
    n : int
        Number of observations.
    omega : float
        Constant in variance equation.
    alpha : float
        ARCH coefficient.
    beta : float
        GARCH coefficient.
    mu : float
        Mean return.
    seed : int
        Random seed for reproducibility.
    start_date : str
        Start date for the business-day index.

    Returns
    -------
    pd.DataFrame
        DataFrame with columns: date, returns, true_volatility.
    """
    rng = np.random.default_rng(seed)
    sigma2 = np.empty(n)
    returns = np.empty(n)
    sigma2[0] = omega / (1 - alpha - beta)

    for t in range(n):
        if t > 0:
            sigma2[t] = omega + alpha * (returns[t - 1] - mu) ** 2 + beta * sigma2[t - 1]
        z = rng.standard_normal()
        returns[t] = mu + np.sqrt(sigma2[t]) * z

    dates = pd.bdate_range(start_date, periods=n)
    return pd.DataFrame(
        {
            "date": dates.strftime("%Y-%m-%d"),
            "returns": np.round(returns, 8),
            "true_volatility": np.round(np.sqrt(sigma2), 8),
        }
    )


def generate_sp500_returns(seed: int = 42) -> pd.DataFrame:
    """Generate synthetic S&P 500 daily returns.

    Calibrated to typical S&P 500 parameters:
    omega=1.5e-6, alpha=0.08, beta=0.91, mu=0.0004.

    Parameters
    ----------
    seed : int
        Random seed (default 42).

    Returns
    -------
    pd.DataFrame
        2500 observations with columns: date, returns, true_volatility.
    """
    return generate_garch11_returns(
        n=2500,
        omega=1.5e-6,
        alpha=0.08,
        beta=0.91,
        mu=0.0004,
        seed=seed,
        start_date="2014-01-02",
    )


def generate_misspecified_data(n: int = 2500, seed: int = 70) -> pd.DataFrame:
    """Generate returns from an EGARCH(1,1) process.

    Data generated by an asymmetric EGARCH process will exhibit sign bias
    when fitted with a symmetric GARCH(1,1) model. The leverage effect
    (gamma < 0) means negative shocks increase volatility more than
    positive shocks of the same magnitude.

    The EGARCH(1,1) model (Nelson 1991):
        ln(sigma2_t) = omega + alpha * |z_{t-1}| + gamma * z_{t-1}
                       + beta * ln(sigma2_{t-1})

    Parameters
    ----------
    n : int
        Number of observations (default 2500).
    seed : int
        Random seed (default 70).

    Returns
    -------
    pd.DataFrame
        DataFrame with columns: date, returns, true_volatility.
    """
    rng = np.random.default_rng(seed)

    # EGARCH parameters with strong asymmetry
    omega = -0.15  # log-variance intercept
    alpha = 0.12  # magnitude effect
    gamma = -0.08  # leverage/asymmetry (negative = leverage effect)
    beta = 0.98  # persistence
    mu = 0.0003

    log_sigma2 = np.empty(n)
    sigma2 = np.empty(n)
    returns = np.empty(n)
    z = np.empty(n)

    # Initialize with unconditional log-variance
    # E[ln(sigma2)] = omega / (1 - beta) when alpha=0, gamma=0
    log_sigma2[0] = omega / (1 - beta)
    sigma2[0] = np.exp(log_sigma2[0])

    for t in range(n):
        if t > 0:
            log_sigma2[t] = (
                omega + alpha * np.abs(z[t - 1]) + gamma * z[t - 1] + beta * log_sigma2[t - 1]
            )
            sigma2[t] = np.exp(log_sigma2[t])

        z[t] = rng.standard_normal()
        returns[t] = mu + np.sqrt(sigma2[t]) * z[t]

    dates = pd.bdate_range("2014-01-02", periods=n)
    return pd.DataFrame(
        {
            "date": dates.strftime("%Y-%m-%d"),
            "returns": np.round(returns, 8),
            "true_volatility": np.round(np.sqrt(sigma2), 8),
        }
    )


def generate_structural_break_data(n: int = 2500, seed: int = 71) -> pd.DataFrame:
    """Generate GARCH(1,1) returns with a structural break at midpoint.

    The first half uses low-volatility parameters and the second half
    switches to high-volatility parameters. This structural break should
    be detectable by the Nyblom stability test, which tests whether
    GARCH parameters are constant over the full sample.

    Regime 1 (t < n/2): omega=1.0e-6, alpha=0.05, beta=0.93
    Regime 2 (t >= n/2): omega=5.0e-6, alpha=0.15, beta=0.80

    Parameters
    ----------
    n : int
        Number of observations (default 2500).
    seed : int
        Random seed (default 71).

    Returns
    -------
    pd.DataFrame
        DataFrame with columns: date, returns, true_volatility, regime.
    """
    rng = np.random.default_rng(seed)

    # Regime 1: low volatility, high persistence
    omega1, alpha1, beta1 = 1.0e-6, 0.05, 0.93
    # Regime 2: high volatility, lower persistence
    omega2, alpha2, beta2 = 5.0e-6, 0.15, 0.80

    mu = 0.0003
    midpoint = n // 2

    sigma2 = np.empty(n)
    returns = np.empty(n)
    regime = np.empty(n, dtype=int)

    # Initialize with regime 1 unconditional variance
    sigma2[0] = omega1 / (1 - alpha1 - beta1)

    for t in range(n):
        if t < midpoint:
            omega, alpha, beta = omega1, alpha1, beta1
            regime[t] = 1
        else:
            omega, alpha, beta = omega2, alpha2, beta2
            regime[t] = 2

        if t > 0:
            sigma2[t] = omega + alpha * (returns[t - 1] - mu) ** 2 + beta * sigma2[t - 1]

        z = rng.standard_normal()
        returns[t] = mu + np.sqrt(sigma2[t]) * z

    dates = pd.bdate_range("2014-01-02", periods=n)
    return pd.DataFrame(
        {
            "date": dates.strftime("%Y-%m-%d"),
            "returns": np.round(returns, 8),
            "true_volatility": np.round(np.sqrt(sigma2), 8),
            "regime": regime,
        }
    )
